Add helm chart unit test foundation
* Add helm unittest files
* Add unittest-charts makefile target
* Add unittest step to CircleCI
* Add helm unittest test file validation script
* Add pre-commit
* Fix shellcheck complaints in create-initial-user
* Check for valid number of args in create-initial-user
* Fix shellcheck complaints in run-ci

diff --git a/bin/create-initial-user b/bin/create-initial-user
--- a/bin/create-initial-user
+++ b/bin/create-initial-user
@@ -1,21 +1,27 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+if [[ ! "${#@}" -eq 2 ]] ; then
+  echo "ERROR: Invalid number of arguments: ${#@}"
+  echo
+  echo "Usage:"
+  echo "    ${0##*/} <user> <pass>"
+  exit 1
+fi
+
+BIN_DIR="${0%/*}"
 
 HOST="https://houston.local.astronomer-development.com/v1"
 
-USER=$1
-PASS=$2
+USER="$1"
+PASS="$2"
 
 ### Make sure we have the same kube creds when needing to be root
-KUBEDIR=$HOME/.kube
-sudo rm -rf /root/.kube
-sudo cp -r $KUBEDIR /root/.kube
+export KUBECONFIG="$HOME/.kube/config"
 
 # So we can talk to houston
-sudo /tmp/bin/kubectl port-forward -n astronomer svc/astronomer-nginx 80 443 &
-FORWARD_PID=$!
+sudo --preserve-env=KUBECONFIG /tmp/bin/kubectl port-forward -n astronomer svc/astronomer-nginx 80 443 &
+FORWARD_PID="$!"
 
 sleep 10
 
@@ -29,16 +35,16 @@ kubectl -n astronomer \
 sed -i \
   -e "s/__USER__/$USER/" \
   -e "s/__PASS__/$PASS/" \
-  $DIR/create-initial-user.json
+  "$BIN_DIR/create-initial-user.json"
 
 # Create new user by posting to houston
 curl -v \
   -H "content-type: application/json" \
-  -d @$DIR/create-initial-user.json \
-  "$HOST" 
+  -d "@$BIN_DIR/create-initial-user.json" \
+  "$HOST"
 
 # restore the JSON file
-git checkout $DIR/create-initial-user.json
+git checkout "$BIN_DIR/create-initial-user.json"
 
 # TODO, trap so that this is always run
-sudo kill -9 $FORWARD_PID
+sudo kill -9 "$FORWARD_PID"
