Add mysql features

diff --git a/bin/install-platform b/bin/install-platform
--- a/bin/install-platform
+++ b/bin/install-platform
@@ -19,40 +19,42 @@ else
 fi
 
 echo "Deploying Astronomer..."
-
-# No args means all
-platform=true
-logging=true
-monitoring=true
-postgresql=true
 ACTION="install"
-dryrun=""
 
-# Any args means be selective
-if [ $# -ne 0 ]; then
+# No args means to use the following settings
+if [[ $# -eq 0 ]]; then
+  platform=true
+  logging=true
+  monitoring=true
+  postgresql=true
+  mysql=false
+  dryrun=""
+else
+  # Any args means be selective
   platform=false
   logging=false
   monitoring=false
   postgresql=false
-  for component in "$@"
-  do
+  mysql=false
+  for component in "$@" ; do
     case $component in
     install)
       ACTION="install" ;;
     template)
       ACTION="template" ;;
     dryrun)
+      echo "Using --dry-run"
       dryrun="--dry-run" ;;
-    all)
-        platform=true
-        logging=true
-        monitoring=true
-        postgresql=true
-      ;;
     *)
-      export "$component"=true ;;
+      echo "Setting ${component}=true"
+      declare "${component}=true" ;;
     esac
   done
+fi
+
+if [[ "${postgresql}" == true ]] && [[ "${mysql}" == true ]]; then
+  echo "ERROR: Cannot enable both postgresql and mysql"
+  exit 1
 fi
 
 set +e
@@ -75,6 +77,7 @@ if ! helm ${ACTION} \
   --set tags.logging="${logging}" \
   --set tags.monitoring="${monitoring}" \
   --set global.postgresqlEnabled="${postgresql}" \
+  --set global.mysqlEnabled="${mysql}" \
   --set astronomer.houston.upgradeDeployments.enabled=true \
   $ASTRONOMER_VERSION_LINE \
   $HELM_CHART_PATH # cannot be quoted because it may contain a glob
diff --git a/bin/reset-local-dev b/bin/reset-local-dev
--- a/bin/reset-local-dev
+++ b/bin/reset-local-dev
@@ -16,6 +16,7 @@ Options:
   -k    List recent kubernetes versions to use with -K (not all will be available to KIND)
   -K    Kubernetes version to use (eg: 1.25.3) https://github.com/kubernetes/kubernetes/releases/
   -M    Enable multi-node kind cluster
+  -d    Database type (postgresql, mysql)
 
 "
 }
@@ -28,8 +29,9 @@ get_kube_versions() {
     sort
 }
 
-while getopts ':hHkK:Mx' option ; do
+while getopts ':hHkK:Mxd:' option ; do
   case "${option}" in
+    d) export DATABASE="${OPTARG}" ;;
     h) usage ; exit 0 ;;
     H) USE_HA=1 ;;
     k) get_kube_versions ; exit 0 ;;
@@ -44,6 +46,7 @@ shift $((OPTIND - 1))
 # The path to the working directory - the root of the repo
 GIT_ROOT="$(git -C "${0%/*}" rev-parse --show-toplevel)"
 NAMESPACE="${NAMESPACE:-astronomer}"
+DATABASE="${DATABASE:-postgresql}"
 
 if [[ -z "${USE_HA+x}" ]]; then
   CONFIG_FILE="$GIT_ROOT/configs/local-dev.yaml"
@@ -51,6 +54,19 @@ if [[ -z "${USE_HA+x}" ]]; then
 else
   CONFIG_FILE="$GIT_ROOT/configs/local-dev-ha.yaml"
   echo "Using HA config file ${CONFIG_FILE##*/}"
+fi
+
+if [[ "${DATABASE}" == postgresql ]] ; then
+  echo "Using postgresql database"
+  ENABLE_POSTGRESQL=true
+  ENABLE_MYSQL=false
+elif [[ "${DATABASE}" == mysql ]] ; then
+  echo "Using mysql database"
+  ENABLE_POSTGRESQL=false
+  ENABLE_MYSQL=true
+else
+  echo "ERROR: Invalid database type: ${DATABASE}"
+  exit 1
 fi
 
 # Fail fast for helm syntax errors
@@ -62,7 +78,8 @@ echo "Deploying Astronomer..."
 helm install -f "$CONFIG_FILE" \
   --timeout "${HELM_INSTALL_TIMEOUT:-800}s" \
   --namespace "${NAMESPACE}" astronomer \
-  --set global.postgresqlEnabled=true \
+  --set global.postgresqlEnabled=${ENABLE_POSTGRESQL} \
+  --set global.mysqlEnabled=${ENABLE_MYSQL} \
   "$GIT_ROOT"
 
 
