Retry kind create cluster once

diff --git a/bin/setup-kind b/bin/setup-kind
--- a/bin/setup-kind
+++ b/bin/setup-kind
@@ -37,8 +37,20 @@ set -xe
 kind delete cluster || true
 
 # Start a cluster
+set +e
 kind create cluster --image kindest/node:${KUBE_VERSION}
+# I have found kind create cluster
+# fails rarely, but since we are running
+# so many in parallel, that it happens
+# enough to justify a retry
+if ! [[ $? -eq 0 ]]; then
+  set -e
+  echo "Failed to create Kind cluster, trying one more time"
+  kind delete cluster || true
+  kind create cluster --image kindest/node:${KUBE_VERSION}
+fi
 
+set -e
 set +x
 
 kubectl get nodes
