Adding Slack notifications.

diff --git a/.circleci/config.yml.j2 b/.circleci/config.yml.j2
--- a/.circleci/config.yml.j2
+++ b/.circleci/config.yml.j2
@@ -8,6 +8,7 @@ executors:
 
 orbs:
   snyk: snyk/snyk@1.1.2
+  slack: circleci/slack@4.10.1
 
 parameters:
   scan-docker-images:
@@ -21,6 +22,9 @@ jobs:
     parameters:
       docker_image:
         type: string
+    environment:
+      SCAN_IMAGE: << parameters.docker_image >>
+      SCAN_TOOL: Snyk
     steps:
       - setup_remote_docker:
           version: {{ remote_docker_version }}
@@ -30,12 +34,28 @@ jobs:
           command: docker pull << parameters.docker_image >>
       - snyk-docker-test:
           docker_image: << parameters.docker_image >>
+      - run:
+          name: Slack Init
+          command: |
+            echo 'export SLACK_MSG_TEMPLATE=$(cat ./.circleci/slack_message_templates/security_scan_fail.json)' >> $BASH_ENV
+            source $BASH_ENV
+          when: always
+      - slack/notify:
+          event: fail
+          template: SLACK_MSG_TEMPLATE
+          channel: C03HS1H9G1E
+
   trivy-scan-docker:
     docker:
       - image: docker:{{ remote_docker_version }}-git
+    shell: /bin/sh -leo pipefail
     parameters:
       docker_image:
         type: string
+    environment:
+      SCAN_IMAGE: << parameters.docker_image >>
+      SCAN_TOOL: Trivy
+      BASH_ENV: /etc/profile
     steps:
       - setup_remote_docker:
           version: {{ remote_docker_version }}
@@ -55,10 +75,21 @@ jobs:
       - run:
           name: Scan the local image with trivy
           command: bin/trivy-scan.sh "<< parameters.docker_image >>" ".circleci/trivyignore"
+      - run:
+          name: Slack Init
+          command: |
+            echo 'export SLACK_MSG_TEMPLATE=$(cat ./.circleci/slack_message_templates/security_scan_fail.json)' >> $BASH_ENV
+            source $BASH_ENV
+          when: on_fail
+      - slack/notify:
+          event: fail
+          template: SLACK_MSG_TEMPLATE
+          channel: C03HS1H9G1E
       - save_cache:
           {% raw %}key: trivy-cache-{{ checksum "date" }}{% endraw %}
           paths:
             - /tmp/workspace/trivy-cache
+
   run_pre_commit:
     docker:
       - image: quay.io/astronomer/ci-pre-commit:2022-05
@@ -128,6 +159,7 @@ jobs:
             venv/bin/python -m pytest -v --junitxml=test-results/junit.xml -n auto $TEST_FILES
       - store_test_results:
           path: test-results
+
   build-artifact:
     docker:
       - image: quay.io/astronomer/ap-build:0.2.0
@@ -217,6 +249,8 @@ workflows:
 {%- for image in docker_images %}
                 - {{ image }}
 {%- endfor %}
+          context:
+            - slack_team-software-infra-bot
       - trivy-scan-docker:
           matrix:
             parameters:
@@ -224,6 +258,9 @@ workflows:
 {%- for image in docker_images %}
                 - {{ image }}
 {%- endfor %}
+          context:
+            - slack_team-software-infra-bot
+
   build-and-release-helm-chart:
     unless:
       and:
