Issue-4620 Docker Image Scan and its notifications to slack (#1558)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,11 +6,95 @@ executors:
     environment:
       GIT_ORG: astronomer
     docker:
-      - image: circleci/python:3
+      - image: cimg/python:3.10
+
+orbs:
+  snyk: snyk/snyk@1.1.2
+  slack: circleci/slack@4.10.1
+
+parameters:
+  scan-docker-images:
+    type: boolean
+    default: false
+    description: "This will run docker image scan."
+
 jobs:
+  snyk-scan-docker:
+    executor: docker-executor
+    parameters:
+      docker_image:
+        type: string
+    environment:
+      SCAN_IMAGE: << parameters.docker_image >>
+      SCAN_TOOL: Snyk
+    steps:
+      - setup_remote_docker:
+          version: 20.10.14
+      - checkout
+      - run:
+          name: Pull Docker image
+          command: docker pull << parameters.docker_image >>
+      - snyk-docker-test:
+          docker_image: << parameters.docker_image >>
+      - run:
+          name: Slack Init
+          command: |
+            echo 'export SLACK_MSG_TEMPLATE=$(cat ./.circleci/slack_message_templates/security_scan_fail.json)' >> $BASH_ENV
+            source $BASH_ENV
+          when: always
+      - slack/notify:
+          event: fail
+          template: SLACK_MSG_TEMPLATE
+          channel: C03HS1H9G1E
+
+  trivy-scan-docker:
+    docker:
+      - image: docker:20.10.14-git
+    shell: /bin/sh -leo pipefail
+    parameters:
+      docker_image:
+        type: string
+    environment:
+      SCAN_IMAGE: << parameters.docker_image >>
+      SCAN_TOOL: Trivy
+      BASH_ENV: /etc/profile
+    steps:
+      - setup_remote_docker:
+          version: 20.10.14
+      - checkout
+      - run:
+          name: Pull Docker image
+          command: docker pull << parameters.docker_image >>
+      - run:
+          name: Install trivy
+          command: |
+            apk add --update-cache --upgrade curl rpm bash
+            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
+            date +%F > date
+      - restore_cache:
+          keys:
+            - trivy-cache-{{ checksum "date" }}
+      - run:
+          name: Scan the local image with trivy
+          command: bin/trivy-scan.sh "<< parameters.docker_image >>" ".circleci/trivyignore"
+      - run:
+          name: Slack Init
+          command: |
+            echo 'export SLACK_MSG_TEMPLATE=$(cat ./.circleci/slack_message_templates/security_scan_fail.json)' >> $BASH_ENV
+            source $BASH_ENV
+          when: on_fail
+      - slack/notify:
+          event: fail
+          template: SLACK_MSG_TEMPLATE
+          channel: C03HS1H9G1E
+      - save_cache:
+          key: trivy-cache-{{ checksum "date" }}
+          paths:
+            - /tmp/workspace/trivy-cache
+
   run_pre_commit:
     docker:
-      - image: quay.io/astronomer/ci-pre-commit:2022-01
+      - image: quay.io/astronomer/ci-pre-commit:2022-05
     steps:
       - checkout
       - run:
@@ -46,7 +130,11 @@ jobs:
   unittest-charts:
     docker:
       - image: quay.io/astronomer/ci-helm-release:2022-01
+    parallelism: 6
     steps:
+      - setup_remote_docker:
+          docker_layer_caching: true
+          version: 20.10.14
       - checkout
       - run:
           name: Create chart-tests-cache-key.txt
@@ -69,7 +157,12 @@ jobs:
             - ~/.local/share/helm/plugins/helm-unittest
       - run:
           name: unittest the Astronomer chart
-          command: make unittest-charts
+          command: |
+            mkdir test-results
+            TEST_FILES=$(circleci tests glob "tests/test_*.py" | circleci tests split --split-by=timings)
+            venv/bin/python -m pytest -v --junitxml=test-results/junit.xml -n auto $TEST_FILES
+      - store_test_results:
+          path: test-results
 
   build-artifact:
     docker:
@@ -168,7 +261,78 @@ jobs:
 
 workflows:
   version: 2.1
+  scan-docker-images:
+    when:
+      and:
+        - << pipeline.parameters.scan-docker-images >>
+    jobs:
+      - snyk-scan-docker:
+          matrix:
+            parameters:
+              docker_image:
+                - quay.io/astronomer/ap-alertmanager:0.23.0
+                - quay.io/astronomer/ap-astro-ui:0.27.17
+                - quay.io/astronomer/ap-base:3.15.1
+                - quay.io/astronomer/ap-cli-install:0.26.2
+                - quay.io/astronomer/ap-commander:0.27.6
+                - quay.io/astronomer/ap-configmap-reloader:0.5.0-1
+                - quay.io/astronomer/ap-curator:5.8.4-11
+                - quay.io/astronomer/ap-db-bootstrapper:0.26.4
+                - quay.io/astronomer/ap-default-backend:0.28.1
+                - quay.io/astronomer/ap-elasticsearch-exporter:1.3.0
+                - quay.io/astronomer/ap-elasticsearch:7.16.3
+                - quay.io/astronomer/ap-fluentd:1.14.5-1
+                - quay.io/astronomer/ap-grafana:8.3.3-1
+                - quay.io/astronomer/ap-houston-api:0.27.18
+                - quay.io/astronomer/ap-kibana:7.16.3
+                - quay.io/astronomer/ap-kube-state:1.7.2
+                - quay.io/astronomer/ap-kubed:0.13.2
+                - quay.io/astronomer/ap-nats-exporter:0.9.1
+                - quay.io/astronomer/ap-nats-exporter:0.9.1-1
+                - quay.io/astronomer/ap-nats-server:2.7.2
+                - quay.io/astronomer/ap-nats-streaming:0.24.1
+                - quay.io/astronomer/ap-nginx-es:1.21.6
+                - quay.io/astronomer/ap-nginx:0.50.0
+                - quay.io/astronomer/ap-node-exporter:1.3.1
+                - quay.io/astronomer/ap-prometheus:2.34.0
+          context:
+            - slack_team-software-infra-bot
+      - trivy-scan-docker:
+          matrix:
+            parameters:
+              docker_image:
+                - quay.io/astronomer/ap-alertmanager:0.23.0
+                - quay.io/astronomer/ap-astro-ui:0.27.17
+                - quay.io/astronomer/ap-base:3.15.1
+                - quay.io/astronomer/ap-cli-install:0.26.2
+                - quay.io/astronomer/ap-commander:0.27.6
+                - quay.io/astronomer/ap-configmap-reloader:0.5.0-1
+                - quay.io/astronomer/ap-curator:5.8.4-11
+                - quay.io/astronomer/ap-db-bootstrapper:0.26.4
+                - quay.io/astronomer/ap-default-backend:0.28.1
+                - quay.io/astronomer/ap-elasticsearch-exporter:1.3.0
+                - quay.io/astronomer/ap-elasticsearch:7.16.3
+                - quay.io/astronomer/ap-fluentd:1.14.5-1
+                - quay.io/astronomer/ap-grafana:8.3.3-1
+                - quay.io/astronomer/ap-houston-api:0.27.18
+                - quay.io/astronomer/ap-kibana:7.16.3
+                - quay.io/astronomer/ap-kube-state:1.7.2
+                - quay.io/astronomer/ap-kubed:0.13.2
+                - quay.io/astronomer/ap-nats-exporter:0.9.1
+                - quay.io/astronomer/ap-nats-exporter:0.9.1-1
+                - quay.io/astronomer/ap-nats-server:2.7.2
+                - quay.io/astronomer/ap-nats-streaming:0.24.1
+                - quay.io/astronomer/ap-nginx-es:1.21.6
+                - quay.io/astronomer/ap-nginx:0.50.0
+                - quay.io/astronomer/ap-node-exporter:1.3.1
+                - quay.io/astronomer/ap-prometheus:2.34.0
+          context:
+            - slack_team-software-infra-bot
+
   build-and-release-helm-chart:
+    unless:
+      and:
+        - << pipeline.parameters.scan-docker-images >>
     jobs:
       - lint
       - run_pre_commit
@@ -238,6 +402,7 @@ commands:
     steps:
       - setup_remote_docker:
           docker_layer_caching: true
+          version: 20.10.14
       - attach_workspace:
           at: /tmp/workspace
       - run:
@@ -291,6 +456,7 @@ commands:
       - checkout
       - setup_remote_docker:
           docker_layer_caching: true
+          version: 20.10.14
       - run:
           name: Build the Docker image
           command: |
@@ -326,6 +492,8 @@ commands:
             echo 'export PATH="/tmp/bin:/tmp/google-cloud-sdk/bin:$PATH"' >> "$HOME/.bashrc"
             set -e
             HELM_CHART_PATH='/tmp/workspace/astronomer-*.tgz' bin/run-ci << parameters.astronomer-tags >>
+      - store_test_results:
+          path: test-results
 
   publish-github-release:
     description: "Create a release on GitHub"
@@ -341,3 +509,24 @@ commands:
             pyenv global 3.9.4
             pip install astronomer_e2e_test
             astronomer-ci publish-github-release --github-repository $CIRCLE_PROJECT_REPONAME --github-organization $CIRCLE_PROJECT_USERNAME --commitish $CIRCLE_SHA1
+
+  snyk-docker-test:
+    description: "Test a Docker image with synk"
+    parameters:
+      docker_image:
+        type: string
+    steps:
+      - snyk/scan:
+          docker-image-name: << parameters.docker_image >>
+          fail-on-issues: true
+          severity-threshold: high
+          monitor-on-build: false
+
+  trivy-docker-test:
+    description: "Trivy: Vulnerability scan a Docker image"
+    parameters:
+      docker_image:
+        type: string
+    steps:
+      - trivy/vulnerability-scan:
+            docker-image: << parameters.docker_image >>
