Notify in slack about CVEs (#1548)
(cherry picked from commit d46aacf2ec9c967fd38667775c930e94153e0870)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,6 +10,7 @@ executors:
 
 orbs:
   snyk: snyk/snyk@1.1.2
+  slack: circleci/slack@4.10.1
 
 parameters:
   scan-docker-images:
@@ -23,6 +24,9 @@ jobs:
     parameters:
       docker_image:
         type: string
+    environment:
+      SCAN_IMAGE: << parameters.docker_image >>
+      SCAN_TOOL: Snyk
     steps:
       - setup_remote_docker:
           version: 20.10.14
@@ -32,12 +36,28 @@ jobs:
           command: docker pull << parameters.docker_image >>
       - snyk-docker-test:
           docker_image: << parameters.docker_image >>
+      - run:
+          name: Slack Init
+          command: |
+            echo 'export SLACK_MSG_TEMPLATE=$(cat ./.circleci/slack_message_templates/security_scan_fail.json)' >> $BASH_ENV
+            source $BASH_ENV
+          when: always
+      - slack/notify:
+          event: fail
+          template: SLACK_MSG_TEMPLATE
+          channel: C03HS1H9G1E
+
   trivy-scan-docker:
     docker:
       - image: docker:20.10.14-git
+    shell: /bin/sh -leo pipefail
     parameters:
       docker_image:
         type: string
+    environment:
+      SCAN_IMAGE: << parameters.docker_image >>
+      SCAN_TOOL: Trivy
+      BASH_ENV: /etc/profile
     steps:
       - setup_remote_docker:
           version: 20.10.14
@@ -57,13 +77,24 @@ jobs:
       - run:
           name: Scan the local image with trivy
           command: bin/trivy-scan.sh "<< parameters.docker_image >>" ".circleci/trivyignore"
+      - run:
+          name: Slack Init
+          command: |
+            echo 'export SLACK_MSG_TEMPLATE=$(cat ./.circleci/slack_message_templates/security_scan_fail.json)' >> $BASH_ENV
+            source $BASH_ENV
+          when: on_fail
+      - slack/notify:
+          event: fail
+          template: SLACK_MSG_TEMPLATE
+          channel: C03HS1H9G1E
       - save_cache:
           key: trivy-cache-{{ checksum "date" }}
           paths:
             - /tmp/workspace/trivy-cache
+
   run_pre_commit:
     docker:
-      - image: quay.io/astronomer/ci-pre-commit:2022-04
+      - image: quay.io/astronomer/ci-pre-commit:2022-05
     steps:
       - checkout
       - run:
@@ -130,6 +161,7 @@ jobs:
             venv/bin/python -m pytest -v --junitxml=test-results/junit.xml -n auto $TEST_FILES
       - store_test_results:
           path: test-results
+
   build-artifact:
     docker:
       - image: quay.io/astronomer/ap-build:0.2.0
@@ -176,52 +208,84 @@ jobs:
             bin/release-helm-chart -p /tmp/workspace/astronomer-*.tgz
       - publish-github-release
 
-  platform-1-19-11:
+  platform-1-19-16:
     machine:
       image: ubuntu-2004:202107-02
       resource_class: xlarge
     environment:
-      KUBE_VERSION: v1.19.11
+      KUBE_VERSION: v1.19.16
     steps:
       - helm-install:
-          astronomer-tags: "platform postgresql monitoring logging kubed keda"
+          astronomer-tags: "platform postgresql monitoring logging"
       - run:
-          name: Check chart for k8s 1.19.11 compatibility with kubent
+          name: Check chart for k8s 1.19.16 compatibility with kubent
           command: |
             set -o pipefail
-            helm template --kube-version=v1.19.11 -f values.yaml --set global.baseDomain=example.com . |
+            helm template --kube-version=v1.19.16 -f values.yaml --set global.baseDomain=example.com . |
             kubent --cluster=false --helm2=false --helm3=false --filename -
           when: always
-  platform-1-20-7:
+  platform-1-20-15:
     machine:
       image: ubuntu-2004:202107-02
       resource_class: xlarge
     environment:
-      KUBE_VERSION: v1.20.7
+      KUBE_VERSION: v1.20.15
     steps:
       - helm-install:
-          astronomer-tags: "platform postgresql monitoring logging kubed keda"
+          astronomer-tags: "platform postgresql monitoring logging"
       - run:
-          name: Check chart for k8s 1.20.7 compatibility with kubent
+          name: Check chart for k8s 1.20.15 compatibility with kubent
           command: |
             set -o pipefail
-            helm template --kube-version=v1.20.7 -f values.yaml --set global.baseDomain=example.com . |
+            helm template --kube-version=v1.20.15 -f values.yaml --set global.baseDomain=example.com . |
             kubent --cluster=false --helm2=false --helm3=false --filename -
           when: always
-  platform-1-21-2:
+  platform-1-21-12:
     machine:
       image: ubuntu-2004:202107-02
       resource_class: xlarge
     environment:
-      KUBE_VERSION: v1.21.2
+      KUBE_VERSION: v1.21.12
     steps:
       - helm-install:
-          astronomer-tags: "platform postgresql monitoring logging kubed keda"
+          astronomer-tags: "platform postgresql monitoring logging"
       - run:
-          name: Check chart for k8s 1.21.2 compatibility with kubent
+          name: Check chart for k8s 1.21.12 compatibility with kubent
           command: |
             set -o pipefail
-            helm template --kube-version=v1.21.2 -f values.yaml --set global.baseDomain=example.com . |
+            helm template --kube-version=v1.21.12 -f values.yaml --set global.baseDomain=example.com . |
+            kubent --cluster=false --helm2=false --helm3=false --filename -
+          when: always
+  platform-1-22-9:
+    machine:
+      image: ubuntu-2004:202107-02
+      resource_class: xlarge
+    environment:
+      KUBE_VERSION: v1.22.9
+    steps:
+      - helm-install:
+          astronomer-tags: "platform postgresql monitoring logging"
+      - run:
+          name: Check chart for k8s 1.22.9 compatibility with kubent
+          command: |
+            set -o pipefail
+            helm template --kube-version=v1.22.9 -f values.yaml --set global.baseDomain=example.com . |
+            kubent --cluster=false --helm2=false --helm3=false --filename -
+          when: always
+  platform-1-23-6:
+    machine:
+      image: ubuntu-2004:202107-02
+      resource_class: xlarge
+    environment:
+      KUBE_VERSION: v1.23.6
+    steps:
+      - helm-install:
+          astronomer-tags: "platform postgresql monitoring logging"
+      - run:
+          name: Check chart for k8s 1.23.6 compatibility with kubent
+          command: |
+            set -o pipefail
+            helm template --kube-version=v1.23.6 -f values.yaml --set global.baseDomain=example.com . |
             kubent --cluster=false --helm2=false --helm3=false --filename -
           when: always
 
@@ -231,7 +295,7 @@ jobs:
     steps:
       - checkout
       - setup_remote_docker:
-          version: 20.10.12
+          version: 20.10.14
       - run:
           name: Check that commander image uses same Airflow chart version
           command: make validate-commander-airflow-version
@@ -247,12 +311,75 @@ workflows:
           matrix:
             parameters:
               docker_image:
-                - 
+                - quay.io/astronomer/ap-alertmanager:0.23.0
+                - quay.io/astronomer/ap-astro-ui:0.29.9
+                - quay.io/astronomer/ap-auth-sidecar:1.21.6-2
+                - quay.io/astronomer/ap-awsesproxy:1.3-4
+                - quay.io/astronomer/ap-base:3.15.4
+                - quay.io/astronomer/ap-blackbox-exporter:0.20.0
+                - quay.io/astronomer/ap-cli-install:0.26.4
+                - quay.io/astronomer/ap-commander:0.29.2
+                - quay.io/astronomer/ap-configmap-reloader:0.5.0-1
+                - quay.io/astronomer/ap-curator:5.8.4-14
+                - quay.io/astronomer/ap-db-bootstrapper:0.26.6
+                - quay.io/astronomer/ap-default-backend:0.28.4
+                - quay.io/astronomer/ap-elasticsearch-exporter:1.3.0
+                - quay.io/astronomer/ap-elasticsearch:7.17.3-1
+                - quay.io/astronomer/ap-fluentd:1.14.6-1
+                - quay.io/astronomer/ap-grafana:8.4.5-3
+                - quay.io/astronomer/ap-houston-api:0.29.23
+                - quay.io/astronomer/ap-kibana:7.17.3-1
+                - quay.io/astronomer/ap-kube-state:1.7.2
+                - quay.io/astronomer/ap-nats-exporter:0.9.2-1
+                - quay.io/astronomer/ap-nats-server:2.8.1
+                - quay.io/astronomer/ap-nats-streaming:0.24.5
+                - quay.io/astronomer/ap-nginx-es:1.21.6-3
+                - quay.io/astronomer/ap-nginx:1.2.0
+                - quay.io/astronomer/ap-node-exporter:1.3.1
+                - quay.io/astronomer/ap-openresty:1.19.9-2
+                - quay.io/astronomer/ap-postgres-exporter:0.10.1
+                - quay.io/astronomer/ap-postgresql:11.15.0
+                - quay.io/astronomer/ap-prometheus:2.34.0
+                - quay.io/astronomer/ap-registry:3.15.4-1
+          context:
+            - slack_team-software-infra-bot
       - trivy-scan-docker:
           matrix:
             parameters:
               docker_image:
-                - 
+                - quay.io/astronomer/ap-alertmanager:0.23.0
+                - quay.io/astronomer/ap-astro-ui:0.29.9
+                - quay.io/astronomer/ap-auth-sidecar:1.21.6-2
+                - quay.io/astronomer/ap-awsesproxy:1.3-4
+                - quay.io/astronomer/ap-base:3.15.4
+                - quay.io/astronomer/ap-blackbox-exporter:0.20.0
+                - quay.io/astronomer/ap-cli-install:0.26.4
+                - quay.io/astronomer/ap-commander:0.29.2
+                - quay.io/astronomer/ap-configmap-reloader:0.5.0-1
+                - quay.io/astronomer/ap-curator:5.8.4-14
+                - quay.io/astronomer/ap-db-bootstrapper:0.26.6
+                - quay.io/astronomer/ap-default-backend:0.28.4
+                - quay.io/astronomer/ap-elasticsearch-exporter:1.3.0
+                - quay.io/astronomer/ap-elasticsearch:7.17.3-1
+                - quay.io/astronomer/ap-fluentd:1.14.6-1
+                - quay.io/astronomer/ap-grafana:8.4.5-3
+                - quay.io/astronomer/ap-houston-api:0.29.23
+                - quay.io/astronomer/ap-kibana:7.17.3-1
+                - quay.io/astronomer/ap-kube-state:1.7.2
+                - quay.io/astronomer/ap-nats-exporter:0.9.2-1
+                - quay.io/astronomer/ap-nats-server:2.8.1
+                - quay.io/astronomer/ap-nats-streaming:0.24.5
+                - quay.io/astronomer/ap-nginx-es:1.21.6-3
+                - quay.io/astronomer/ap-nginx:1.2.0
+                - quay.io/astronomer/ap-node-exporter:1.3.1
+                - quay.io/astronomer/ap-openresty:1.19.9-2
+                - quay.io/astronomer/ap-postgres-exporter:0.10.1
+                - quay.io/astronomer/ap-postgresql:11.15.0
+                - quay.io/astronomer/ap-prometheus:2.34.0
+                - quay.io/astronomer/ap-registry:3.15.4-1
+          context:
+            - slack_team-software-infra-bot
+
   build-and-release-helm-chart:
     unless:
       and:
@@ -271,15 +398,25 @@ workflows:
       - approve-test-all-platforms:
           type: approval
 
-      - platform-1-19-11:
+      - platform-1-19-16:
           requires:
             - build-artifact
-      - platform-1-20-7:
+      - platform-1-20-15:
           requires:
             - approve-test-all-platforms
             - build-artifact
 
-      - platform-1-21-2:
+      - platform-1-21-12:
+          requires:
+            - approve-test-all-platforms
+            - build-artifact
+
+      - platform-1-22-9:
+          requires:
+            - approve-test-all-platforms
+            - build-artifact
+
+      - platform-1-23-6:
           requires:
             - build-artifact
       - approve-internal-release:
@@ -289,13 +426,15 @@ workflows:
             - gcp-astronomer-prod
           requires:
             - approve-internal-release
-            - platform-1-19-11
-            - platform-1-21-2
+            - platform-1-19-16
+            - platform-1-23-6
       - approve-public-release:
           type: approval
           requires:
             - release-to-internal
-            - platform-1-20-7
+            - platform-1-20-15
+            - platform-1-21-12
+            - platform-1-22-9
           filters:
             branches:
               only:
@@ -420,6 +559,7 @@ commands:
             HELM_CHART_PATH='/tmp/workspace/astronomer-*.tgz' bin/run-ci << parameters.astronomer-tags >>
       - store_test_results:
           path: test-results
+
   publish-github-release:
     description: "Create a release on GitHub"
     parameters:
