Notify in slack about CVEs (#1548)
(cherry picked from commit d46aacf2ec9c967fd38667775c930e94153e0870)

diff --git a/.circleci/config.yml.j2 b/.circleci/config.yml.j2
--- a/.circleci/config.yml.j2
+++ b/.circleci/config.yml.j2
@@ -8,6 +8,7 @@ executors:
 
 orbs:
   snyk: snyk/snyk@1.1.2
+  slack: circleci/slack@4.10.1
 
 parameters:
   scan-docker-images:
@@ -16,6 +17,79 @@ parameters:
     description: "This will run docker image scan."
 
 jobs:
+  snyk-scan-docker:
+    executor: docker-executor
+    parameters:
+      docker_image:
+        type: string
+    environment:
+      SCAN_IMAGE: << parameters.docker_image >>
+      SCAN_TOOL: Snyk
+    steps:
+      - setup_remote_docker:
+          version: {{ remote_docker_version }}
+      - checkout
+      - run:
+          name: Pull Docker image
+          command: docker pull << parameters.docker_image >>
+      - snyk-docker-test:
+          docker_image: << parameters.docker_image >>
+      - run:
+          name: Slack Init
+          command: |
+            echo 'export SLACK_MSG_TEMPLATE=$(cat ./.circleci/slack_message_templates/security_scan_fail.json)' >> $BASH_ENV
+            source $BASH_ENV
+          when: always
+      - slack/notify:
+          event: fail
+          template: SLACK_MSG_TEMPLATE
+          channel: C03HS1H9G1E
+
+  trivy-scan-docker:
+    docker:
+      - image: docker:{{ remote_docker_version }}-git
+    shell: /bin/sh -leo pipefail
+    parameters:
+      docker_image:
+        type: string
+    environment:
+      SCAN_IMAGE: << parameters.docker_image >>
+      SCAN_TOOL: Trivy
+      BASH_ENV: /etc/profile
+    steps:
+      - setup_remote_docker:
+          version: {{ remote_docker_version }}
+      - checkout
+      - run:
+          name: Pull Docker image
+          command: docker pull << parameters.docker_image >>
+      - run:
+          name: Install trivy
+          command: |
+            apk add --update-cache --upgrade curl rpm bash
+            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
+            date +%F > date
+      - restore_cache:
+          keys:
+            {% raw %}- trivy-cache-{{ checksum "date" }}{% endraw %}
+      - run:
+          name: Scan the local image with trivy
+          command: bin/trivy-scan.sh "<< parameters.docker_image >>" ".circleci/trivyignore"
+      - run:
+          name: Slack Init
+          command: |
+            echo 'export SLACK_MSG_TEMPLATE=$(cat ./.circleci/slack_message_templates/security_scan_fail.json)' >> $BASH_ENV
+            source $BASH_ENV
+          when: on_fail
+      - slack/notify:
+          event: fail
+          template: SLACK_MSG_TEMPLATE
+          channel: C03HS1H9G1E
+      - save_cache:
+          {% raw %}key: trivy-cache-{{ checksum "date" }}{% endraw %}
+          paths:
+            - /tmp/workspace/trivy-cache
+
   run_pre_commit:
     docker:
       - image: quay.io/astronomer/ci-pre-commit:2022-05
@@ -85,6 +159,7 @@ jobs:
             venv/bin/python -m pytest -v --junitxml=test-results/junit.xml -n auto $TEST_FILES
       - store_test_results:
           path: test-results
+
   build-artifact:
     docker:
       - image: quay.io/astronomer/ap-build:0.2.0
@@ -174,6 +249,8 @@ workflows:
 {%- for image in docker_images %}
                 - {{ image }}
 {%- endfor %}
+          context:
+            - slack_team-software-infra-bot
       - trivy-scan-docker:
           matrix:
             parameters:
@@ -181,7 +258,13 @@ workflows:
 {%- for image in docker_images %}
                 - {{ image }}
 {%- endfor %}
+          context:
+            - slack_team-software-infra-bot
+
   build-and-release-helm-chart:
+    unless:
+      and:
+        - << pipeline.parameters.scan-docker-images >>
     jobs:
       - lint
       - run_pre_commit
